### ISSUE TITLE
not adding logs to correct log arrag

### ISSUE THREAD

**Issue by davidmaxwaterman** [sunnykgupta/jsLogger#3]
> logArray.logs.push(arguments);

This logs all the different types of errors to the logs array, when it should presumably log them to the one corresponding to the log method called....ie, all messages go into logArray.logs[].

**Comment by sunnykgupta** [comment]
Would you like to submit a pull-request for the change?

**Comment by sunnykgupta** [comment]
@davidmaxwaterman - thanks for catching this.
